#!/usr/bin/env python3
"""
PHASE 1: MASSIVE DELETION - EXECUTION SCRIPT
Executes the deletion of contaminated and unnecessary files.

REQUIRES: DELETION_REPORT.json (generated by scan_deletion_targets.py)
"""

from pathlib import Path
import json
import os
import shutil

PROJECT_ROOT = Path(".")


def load_deletion_report():
    """Load deletion report."""
    report_file = PROJECT_ROOT / "DELETION_REPORT.json"

    if not report_file.exists():
        raise FileNotFoundError(
            "DELETION_REPORT.json not found. "
            "Run scripts/scan_deletion_targets.py first."
        )

    with open(report_file, 'r') as f:
        return json.load(f)


def execute_deletion(report, dry_run=False):
    """Execute deletion of files."""

    deleted_count = 0
    failed_count = 0
    deleted_size = 0

    print("=" * 80)
    if dry_run:
        print("DRY RUN - Files will NOT be deleted")
    else:
        print("EXECUTING DELETION")
    print("=" * 80)

    for file_info in report["files"]:
        filepath = Path(file_info["path"])
        category = file_info["category"]
        size = file_info["size_bytes"]

        if not filepath.exists():
            print(f"⚠️  SKIP: {filepath} (already deleted)")
            continue

        try:
            if dry_run:
                print(f"🔍 WOULD DELETE: {filepath} ({size:,} bytes) [{category}]")
                deleted_count += 1
                deleted_size += size
            else:
                # Actually delete
                if filepath.is_file():
                    filepath.unlink()
                elif filepath.is_dir():
                    shutil.rmtree(filepath)

                print(f"✅ DELETED: {filepath} ({size:,} bytes) [{category}]")
                deleted_count += 1
                deleted_size += size

        except Exception as e:
            print(f"❌ FAILED: {filepath} - {str(e)}")
            failed_count += 1

    # Summary
    print("\n" + "=" * 80)
    print("DELETION SUMMARY")
    print("=" * 80)
    print(f"{'Mode:':<20} {'DRY RUN' if dry_run else 'EXECUTED'}")
    print(f"{'Files deleted:':<20} {deleted_count}/{report['total_files']}")
    print(f"{'Failed:':<20} {failed_count}")
    print(f"{'Space freed:':<20} {deleted_size:,} bytes ({deleted_size / 1024 / 1024:.2f} MB)")

    return deleted_count, failed_count


def main():
    """Main entry point."""

    # Load report
    report = load_deletion_report()

    print("Deletion plan loaded:")
    print(f"  Total files: {report['total_files']}")
    print(f"  Total size: {report['total_size_bytes']:,} bytes ({report['total_size_bytes'] / 1024 / 1024:.2f} MB)")
    print()

    # Ask for confirmation
    print("⚠️  WARNING: This will permanently delete 44 files (4.67 MB)")
    print("   All files are backed up in MIGRATION_ARTIFACTS_FAKE_TO_REAL/")
    print()
    response = input("Type 'DELETE' to confirm deletion: ")

    if response != "DELETE":
        print("\n❌ Deletion cancelled.")
        print("To see what would be deleted, run with --dry-run:")
        print("  python3 scripts/execute_deletion.py --dry-run")
        return

    # Execute deletion
    print()
    deleted, failed = execute_deletion(report, dry_run=False)

    # Final status
    print()
    if failed == 0 and deleted == report['total_files']:
        print("✅ DELETION COMPLETE - All files successfully deleted")
        print()
        print("Next steps:")
        print("1. Commit the deletions: git add -A && git commit -m 'chore: Phase 1 massive deletion'")
        print("2. Proceed to Phase 2: Folder restructuring")
    else:
        print(f"⚠️  DELETION INCOMPLETE - {failed} failures")


if __name__ == "__main__":
    import sys

    # Check for dry-run flag
    if "--dry-run" in sys.argv:
        report = load_deletion_report()
        execute_deletion(report, dry_run=True)
    else:
        main()
